version: '3.8'

services:
  react-app:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - envoy
      # - certbot
    volumes:
      - /etc/letsencrypt/live/schaty.net:/etc/nginx/certs:ro # 証明書をコンテナにマウント

  envoy:
    image: envoyproxy/envoy:v1.15.0
    container_name: envoy-grpc-proxy_with-react-app
    ports:
      - "9000:9000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/lib/letsencrypt:/var/lib/letsencrypt
  #     # - /usr/share/nginx/html:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --webroot --webroot-path=/usr/share/nginx/html -d schaty.net; exec /bin/sh -c \"trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;\"'"