FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

# 証明書を置くためのディレクトリを作成
RUN mkdir -p /etc/nginx/certs

# envoyのデフォルト設定ファイルなどの削除 & 設定ファイルのコピー等を行う
COPY --from=builder /app/build /usr/share/nginx/html

# Nginxの設定ファイルテンプレートをコピー
COPY nginx.conf.template /etc/nginx/templates/nginx.conf.template