version: '3.8'

services:
  react-app:
    build:
      context: ./
      dockerfile: Dockerfile.react
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    depends_on:
      - envoy
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    environment:
      - FRONT_SERVER_DOMAIN=${FRONT_SERVER_DOMAIN}
      - BACK_SERVER_DOMAIN=${BACK_SERVER_DOMAIN}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - BACKEND_SERVER_PORT=${BACKEND_SERVER_PORT}
      - GRPC_PROXY_PORT=${GRPC_PROXY_PORT}
      - GRPC_PORT=${GRPC_PORT}
    networks:
      - app-network
    command: /bin/sh -c "envsubst '$$FRONT_SERVER_DOMAIN$$BACK_SERVER_DOMAIN$$HTTP_PORT$$HTTPS_PORT$$BACKEND_SERVER_PORT$$GRPC_PROXY_PORT$$GRPC_PORT' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

  envoy:
    build:
      context: ./
      dockerfile: Dockerfile.envoy
    container_name: envoy-grpc-proxy_with-react-app
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./envoy.yaml.template:/etc/envoy/envoy.yaml.template
    environment:
      - GRPC_PROXY_PORT=${GRPC_PROXY_PORT}
      - GRPC_PORT=${GRPC_PORT}
      - BACK_SERVER_DOMAIN=${BACK_SERVER_DOMAIN}
    networks:
      - app-network
    command: /bin/sh -c "rm /etc/envoy/envoy.yaml && envsubst '$$GRPC_PROXY_PORT$$GRPC_PORT$$BACK_SERVER_DOMAIN' < /etc/envoy/envoy.yaml.template > /etc/envoy/envoy.yaml && exec envoy -c /etc/envoy/envoy.yaml"

networks:
  app-network:
    driver: bridge