version: '3.8'

services:
  react-app:
    build:
      context: ./
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - envoy
    volumes:
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    networks:
      - app-network

  envoy:
    image: envoyproxy/envoy:v1.17-latest
    container_name: envoy-grpc-proxy_with-react-app
    ports:
      - "9000:9000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - app-network
    command: ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]

networks:
  app-network:
    driver: bridge