/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0-rc1
// source: src/proto/message.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as src_proto_message_pb from '../../src/proto/message_pb'; // proto import: "src/proto/message.proto"


export class MessageServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetMessages = new grpcWeb.MethodDescriptor(
    '/proto.MessageService/GetMessages',
    grpcWeb.MethodType.UNARY,
    src_proto_message_pb.GetMessageRequest,
    src_proto_message_pb.GetMessagesResponse,
    (request: src_proto_message_pb.GetMessageRequest) => {
      return request.serializeBinary();
    },
    src_proto_message_pb.GetMessagesResponse.deserializeBinary
  );

  getMessages(
    request: src_proto_message_pb.GetMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<src_proto_message_pb.GetMessagesResponse>;

  getMessages(
    request: src_proto_message_pb.GetMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: src_proto_message_pb.GetMessagesResponse) => void): grpcWeb.ClientReadableStream<src_proto_message_pb.GetMessagesResponse>;

  getMessages(
    request: src_proto_message_pb.GetMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: src_proto_message_pb.GetMessagesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.MessageService/GetMessages',
        request,
        metadata || {},
        this.methodDescriptorGetMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.MessageService/GetMessages',
    request,
    metadata || {},
    this.methodDescriptorGetMessages);
  }

  methodDescriptorConnect = new grpcWeb.MethodDescriptor(
    '/proto.MessageService/Connect',
    grpcWeb.MethodType.SERVER_STREAMING,
    src_proto_message_pb.ConnectRequest,
    src_proto_message_pb.MessageResponse,
    (request: src_proto_message_pb.ConnectRequest) => {
      return request.serializeBinary();
    },
    src_proto_message_pb.MessageResponse.deserializeBinary
  );

  connect(
    request: src_proto_message_pb.ConnectRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<src_proto_message_pb.MessageResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/proto.MessageService/Connect',
      request,
      metadata || {},
      this.methodDescriptorConnect);
  }

}

